from common.models.statuses.MinionStatus import MinionStatus
from pydantic import BaseModel
from datetime import datetime


class MinionHealth(BaseModel):
    status: MinionStatus
    timestamp: datetime = datetime.now().isoformat() # validate that when master receives it, it is the timestamp from minion and not generated by master. (or just not set default value)